### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)

### ISSUE THREAD

**Issue by thealteria** [jonataslaw/get_storage#56] opened 2021-03-18 06:18 UTC
As I'm using the `get_storage` in my app, my app freezes on the startup showing the white screen while building the release apk.
Getting the following error:

```
[+2458 ms] E/flutter (11801): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception:
MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel        
plugins.flutter.io/path_provider)
[   +2 ms] E/flutter (11801): #0      GetStorage._init (package:get_storage/src/storage_impl.dart:47)        
[   +1 ms] E/flutter (11801): <asynchronous suspension>
[   +1 ms] E/flutter (11801): #1      new GetStorage._internal.<anonymous closure>
(package:get_storage/src/storage_impl.dart:28)
[   +1 ms] E/flutter (11801): <asynchronous suspension>
[   +1 ms] E/flutter (11801): #2      Initializer._initStorage
(package:scm_study/app/common/util/initializer.dart:22)
[   +1 ms] E/flutter (11801): <asynchronous suspension>
[        ] E/flutter (11801): #3      Initializer.init
(package:scm_study/app/common/util/initializer.dart:12)
[   +1 ms] E/flutter (11801): <asynchronous suspension>
[   +1 ms] E/flutter (11801): #4      main (package:scm_study/main.dart:13)
[        ] E/flutter (11801): <asynchronous suspension>
[   +1 ms] E/flutter (11801): 
```

**Comment by aiuric** [comment] 2021-03-19 08:44
me too!

**Comment by rodrigorafaeldamaceno** [comment] 2021-03-19 20:14
me too!

**Comment by rodrigorafaeldamaceno** [comment] 2021-03-19 20:31
me too! only in release mode.

**Comment by jonataslaw** [comment] 2021-03-20 18:32
duplicate of https://github.com/jonataslaw/get_storage/issues/33

**Closed by jonataslaw** 2021-03-20 18:32 UTC
